### ISSUE TITLE
Date controller contains wrong selected date

### ISSUE THREAD

**Issue by TatsuUkraine** [JonasWanke/timetable#79] opened 2021-06-10 21:00 UTC
**Describe the bug**
**Story**
- open example project
- switch to 3 days view
- scroll to state when Today (sometimes day after today) is a first one in 3 days list
- swipe less than 40% width of the day column in the past
- remove finger so time table return back to original date

**Expected behavior**
Date controller emits (has) date that 3 days interval start with

**Actual behavior**
Date controller has date that is one day before the actual one

**Screenshots**

https://user-images.githubusercontent.com/621542/121596282-ea75a780-ca47-11eb-876c-8e67e2fd84d6.mov

**Environment:**
- Device:  Android Pixel 3 emulator/Android pixel 5 real device
- OS version:  Android 11
- Package version:  1.0.0-alpha.1

**Comment by paolovalerdi** [comment] 2021-07-07 18:30
The `DateController`  says:

> The correct value is set via the listener when we assign it to our value.

So I think the correct way to access the current date would be: `_timeController.value.date`.

**Comment by TatsuUkraine** [comment] 2021-07-07 18:45
@paolovalerdi I didn't try time controller, but case here that I was able to reproduce it only on android. And the second problem I may see here is that when value on the controller is incorrect, you won't be able to change it programmatically, like in this example, on one day in the past, since from the value notifier standpoint - value didn't change

**Comment by TatsuUkraine** [comment] 2021-07-07 18:49
@paolovalerdi also, I don't see `date` prop in `TimeRange` object (value of time controller)

**Comment by paolovalerdi** [comment] 2021-07-07 18:53
@TatsuUkraine my bad, I meant _dateController 🙃

**Comment by paolovalerdi** [comment] 2021-07-07 19:06
@TatsuUkraine nvm, I think the issue is indeed in the controller.
I think the problem is the `page.floor()` inside of the value object

Can you try the following thing? 

`final correctDate = DateTimeTimetable.dateFromPage(_dateController.value.page.round());`

**Comment by TatsuUkraine** [comment] 2021-07-07 19:21
@paolovalerdi I'm not using alpha now so can't check) there's a good amount of different issues, that block me from moving to alpha at this point unfortunately ((

**Comment by TatsuUkraine** [comment] 2021-07-07 19:24
Biggest one is this one #73, I wasn't been able to find a proper steps to reproduce for now

**Comment by JonasWanke** [comment] 2021-07-15 10:31
This had the same root cause as #86: The reported position was something like `18861.9999999851` (instead of `18862`) and hence the date was wrong. But it's now fixed in release [v1.0.0-alpha.2](https://pub.dev/packages/timetable/versions/1.0.0-alpha.2/changelog#100-alpha2--2021-07-15).

**Closed by JonasWanke** 2021-07-15 10:31 UTC
Labels: T: fix

**Comment by TatsuUkraine** [comment] 2021-07-15 13:57
@JonasWanke just curious, could this issue cause problem described in #73 ?

**Comment by JonasWanke** [comment] 2021-07-15 14:37
@TatsuUkraine I don't think so, but I haven't yet been able to reproduce that issue
